# Generated by Django 3.1 on 2020-08-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('date_joined', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('transport_mode', models.CharField(max_length=6)),
            ],
        ),
    ]
