# Generated by Django 3.1 on 2020-09-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_delivery_dispensercoolerbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingprovider',
            name='date_joined',
            field=models.DateTimeField(),
        ),
    ]
