# Generated by Django 3.1 on 2020-08-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=6)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
