# Generated by Django 3.1 on 2020-09-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_cart_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(max_length=7),
        ),
    ]
